// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7eu_INx8iKUG1QcYpvliSBFjZklLSm7g',
    appId: '1:544162802806:web:4dd8c50f731c846652c357',
    messagingSenderId: '544162802806',
    projectId: 'login-app-f17a8',
    authDomain: 'login-app-f17a8.firebaseapp.com',
    storageBucket: 'login-app-f17a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28V4udo71g2z_gYuBRdfBcpK7I_4PDig',
    appId: '1:544162802806:android:ffa2cde0fc18b26c52c357',
    messagingSenderId: '544162802806',
    projectId: 'login-app-f17a8',
    storageBucket: 'login-app-f17a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYrB7Q7R6IKvGAtBPi2N6gnA7QfABN8Bg',
    appId: '1:544162802806:ios:b57b6277833e48b052c357',
    messagingSenderId: '544162802806',
    projectId: 'login-app-f17a8',
    storageBucket: 'login-app-f17a8.appspot.com',
    iosClientId: '544162802806-3ur0movkm1qog3mti0lvf2lpu6pi9ibf.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYrB7Q7R6IKvGAtBPi2N6gnA7QfABN8Bg',
    appId: '1:544162802806:ios:b57b6277833e48b052c357',
    messagingSenderId: '544162802806',
    projectId: 'login-app-f17a8',
    storageBucket: 'login-app-f17a8.appspot.com',
    iosClientId: '544162802806-3ur0movkm1qog3mti0lvf2lpu6pi9ibf.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );
}
